export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPE_BY_ID_SUCCESS = 'GET_RECIPE_BY_ID_SUCCESS';
export const CREAT_RECIPE_SUCCESS = 'CREAT_RECIPE_SUCCESS';
export const REMOVE_RECIPE_SUCCESS = 'REMOVE_RECIPE_SUCCESS';
